### ISSUE TITLE
Where is the source to the exe in this repository?

### ISSUE THREAD

**Issue by SynnKo** [pokerobybeto/Ultimate-Stream-Tool#3]
Might seem like a strange question and maybe it's just me, but when I look at a repository on GitHub, I usually expect to see the entire source code of a given project. You don't usually see a binary file like an exe in a repository, those are usually reserved for releases.

While it's not a big deal, since it still allows for a lot of customization, I do want to know: where did that exe come from? Is it open source? Is there a way I can build it myself? It's not that I don't trust this project, but I do find the sight of an exe in a repository a little ugly, and it seems the projects before this one all did it the same way, unfortunately. Again, just personal preference, I just want to be able to build the entire project myself.

**Comment by pokerobybeto** [comment]
The source code is not available for now.  Unlike the previous projects, which had been commissioned more than fine, I made this tool without any commission and without earning anything. Even after I released it, I had a single donation and very few commissions. So I don't care if "you find the sight of an exe in a repository a little ugly". I prefer to keep my unpaid work and make some profit out of that. If you think that my work is worth nothing, because from this message I understand this, you are free to take the source code from some other tool and use that instead.

**Comment by SynnKo** [comment]
"If you think that my work is worth nothing, because from this message I understand this ..."

If that's really what you understood, then I guess either English isn't your first language or you're exceptionally sensitive to even the mildest form of criticism. I even said myself that it's not a big deal, so I don't understand why you get so butt-hurt over it. But hey, it's your project, you can do whatever you want with it. I just wanted to know where the source of the exe is, that's all. If you say it's not available, I would've been fine with that, but you took it weirdly personal for some reason.

At least I know now that if I ever decided to make my own tool, I have a good reason to do it. Thank you for clarifying. Have a great day. :)
